version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_api
    restart: always
    # Cargamos las variables del .env para que main.py las reconozca
    env_file:
      - .env
    ports:
      - "${PUERTO_API}:8000"
    # Esta configuración permite que el contenedor vea servicios en el host del VPS
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: fastapi_network